### PR TITLE
Kill reactor properly

### LINKED ISSUE #10: Elm Reactor: Stop leaves elm reactor running (windows)
I ran "elm reactor - start" command, "elm reactor - stop" command. If I run "elm reactor - stop" again it says elm reactor is not running, but the process is still running (and if I visit the site, I can see the webserver is still running).

Platform: Win 7

### PR DESCRIPTION
**Pull request by rojepp**
Fixes #10, tested on OSX only.

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
I'm not sure if it's enough - in Ionide we do something like that to kill processes on Windows https://github.com/ionide/ionide-vscode-fake/blob/master/src/fake.fs#L51-L55

**Comment by rojepp** [comment]
Thanks! A combination of the two worked.

**Comment by rojepp** [comment]
Probably reactor should also be killed when code exits?

**Comment by Krzysztof-Cieslak** [comment]
I think child processes are killed when node applications exists.

**Comment by rojepp** [comment]
Reactor process still lives on Windows after I quit code. I'll check OSX tomorrow.

**Comment by Krzysztof-Cieslak** [comment]
Looks like it's problem in VS Code indeed, https://github.com/Microsoft/vscode-go/issues/26

**Comment by rojepp** [comment]
We can just call a silent version `stopReactor` on process exit? I'll do that in a few hours.

**Comment by Krzysztof-Cieslak** [comment]
It was discussed in issue I've linked, looks like there are some problems with that.

**Comment by rojepp** [comment]
We could probably implement some hack to do it, but I'd prefer waiting for [vscode support for deactivation](https://github.com/Microsoft/vscode/issues/537). I'd say this PR is ready to merge.

**Comment by Krzysztof-Cieslak** [comment]
:+1:

**Pull request merged**
