### PR TITLE
Find project root folder

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**
Recursive finding starting from folder of active file editor and going through all ancestors.

### CODE REVIEW

**Comment by rojepp** [comment]
I havent tested this in an elm project (I don't have this error myself). I did write a test for `findProj` and it seems to work. LGTM. Should I push the test to this branch?

**Comment by Krzysztof-Cieslak** [comment]
Yes, please. I guess we should generally add more tests for this project... maybe even set up CI?

**Comment by rojepp** [comment]
CI would be great!

**Comment by Krzysztof-Cieslak** [comment]
Generally agree, it's probably worth discussing in separate issue.

**Comment by rojepp** [comment]
This PR looks good to go?

**Comment by Krzysztof-Cieslak** [comment]
LGTM

**Pull request merged**
